CA-277 implement service perimeters rebased
broadinstitute/rawls pull request #1103
Opened 2019-06-21 15:47 UTC by marctalbott

These are the same changes that you'll see in #1100 but I've cherry-picked those changes onto a new branch with the most recent dev changes.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check that the **Product Owner** has signed off on any user-facing changes
- [ ] **Submitter**: Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Database checks:
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] Tell your tech lead (TL) that the PR exists if they want to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2019-06-25 13:39 UTC, dvoet approved these changes

2019-06-26 14:44 UTC, gpolumbo-broad requested changes

2019-06-26 14:44 UTC, gpolumbo-broad commented on core/src/main/resources/swagger/api-docs.yaml
> +          description: You must be a user of the google billing account and have permissions on the service perimeter
`You must be a user of the google billing account and have permissions on the service perimeter if one is specified`

2019-06-26 14:44 UTC, gpolumbo-broad commented on core/src/main/scala/org/broadinstitute/dsde/rawls/user/UserService.scala
> +      //NOTE: we're syncing this to Sam ahead of the resource actually existing. is this fine? (ps these are sam calls)
Don't know.  Is this fine?  I think we should answer this question and remove this comment to avoid confusing future engineers who read this.

2019-06-26 14:58 UTC, gpolumbo-broad approved these changes

2019-06-28 14:43 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/user/UserService.scala
> +      //NOTE: we're syncing this to Sam ahead of the resource actually existing. is this fine? (ps these are sam calls)
yes, it's fine. i added this comment a while back and doug has told me it's fine. it keeps coming up so i agree we should nuke it

2019-06-28 16:01 UTC, merged