[CA-1460] Delete Errored V1 Billing Projects
broadinstitute/rawls pull request #1541
Opened 2021-10-05 18:13 UTC by ehigham

RR: https://broadworkbench.atlassian.net/browse/CA-1460

When a user creates a v1 billing account, rawls creates the resource for the google project in sam BEFORE it creates the google project proper. If the project creation fails, we delete the project from rawl’s database but we never tell sam.

When listing billing projects, we ask sam for all resources with resource type billing project. Since it doesn’t know that the billing project and google project don’t exist, it returns us all the resources AS IF it existed.

TLDR; we can’t trust that a resource exists just because sam says it does. This is seems reasonable because a user could stab us in the back and delete these resources in google and we’d be in the same situation.

Fix: Test that google project that backs the billing project exists before trying to delete it.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check that the **Product Owner** has signed off on any user-facing changes
- [ ] **Submitter**: Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Database checks:
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] Tell your tech lead (TL) that the PR exists if they want to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2021-10-12 17:02 UTC, gpolumbo-broad commented
Great description of the PR!

2021-10-12 18:04 UTC, andy7i commented on google/src/main/scala/org/broadinstitute/dsde/rawls/google/GoogleUtilities.scala
> +      case t: HttpResponseException if t.getStatusCode/100 == 4 => t.getStatusCode != 404
I haven't looked too deeply into this, but I'm worried that this changes the behavior for many calls to google, since `when500orGoogleError` is used in `retryWhen500orGoogleError` and `retryWithRecoverWhen500orGoogleError`, which are used 50+ times between the two. What are your thoughts on this?

2021-10-12 18:07 UTC, ehigham commented on google/src/main/scala/org/broadinstitute/dsde/rawls/google/GoogleUtilities.scala
> +      case t: HttpResponseException if t.getStatusCode/100 == 4 => t.getStatusCode != 404
Yeah, this is a big change and I discussed it in slack in https://broadinstitute.slack.com/archives/C2B7JFJ4S/p1633451415146700.
The TLDR is I think we should give special handling to 404 errors and not just roll it up into default handling for "`GoogleError`s". If it's a case where 404s should be handled by retries, then that's easy enough to add back for those cases.
I COULD have added a new interface method for this but decided against that as:
- It's not true - 404s don't mean that the google project doesn't exist
- It would have incurred more tech debt

2021-10-12 19:26 UTC, gpolumbo-broad requested changes

2021-10-12 19:26 UTC, gpolumbo-broad commented on core/src/main/scala/org/broadinstitute/dsde/rawls/user/UserService.scala
> +    def googleProjectExists(projectId: GoogleProjectId) =
Not sure if we've ever decided on a convention for declaring the return type, but I would opt to always include it.

2021-10-12 19:26 UTC, gpolumbo-broad commented on core/src/main/scala/org/broadinstitute/dsde/rawls/user/UserService.scala
> +      gcsDAO.getGoogleProject(projectId) transform {
TIL - [Future.transform](https://www.scala-lang.org/api/2.13.6/scala/concurrent/Future.html#transform[S](f:scala.util.Try[T]=%3Escala.util.Try[S])(implicitexecutor:scala.concurrent.ExecutionContext):scala.concurrent.Future[S]) thanks!

2021-10-12 19:26 UTC, gpolumbo-broad commented on core/src/main/scala/org/broadinstitute/dsde/rawls/user/UserService.scala
> +            Future.unit)
I'm on the fence as to requesting this line to be extracted into its own method.  It has a lot going on in one expression with a couple layers of nesting, which is elegant, but not necessarily the easiest to read at first glance (in my opinion).  As is, I think it is fine, but if I needed to modify this or add to it, the first thing I would do would be to extract it.  So I guess what I'm saying is that if you were on the fence about extracting a method here, I'd say do it.  If you're happy/prefer it as is, then it is fine with me to keep it as is.

2021-10-12 19:26 UTC, gpolumbo-broad commented on core/src/test/scala/org/broadinstitute/dsde/rawls/user/UserServiceSpec.scala
> +  it should "Successfully to delete a billing project when the google project does not exist" in {
```suggestion
  it should "Successfully to delete a billing project when the google project does not exist on GCP" in {
```

Just want to be explicit because there are `google-project` Resources that exist in Sam too

2021-10-12 20:04 UTC, ehigham commented on core/src/main/scala/org/broadinstitute/dsde/rawls/user/UserService.scala
> +    def googleProjectExists(projectId: GoogleProjectId) =
I would agree for exported functions for documentation purposes - for simple helpers and predicates I don't think it adds much.

2021-10-12 22:22 UTC, ehigham commented on core/src/main/scala/org/broadinstitute/dsde/rawls/user/UserService.scala
> +            Future.unit)
I've tried to make it more readable. I think people are more familiar with `for` comprehensions rather than `*>` so I've reverted to that. Let me know what you think.

2021-10-13 14:23 UTC, andy7i approved these changes
I'm still a bit wary of changing the behavior of `when500orGoogleError`, since this could fail with new cloud resources and may be difficult to debug. Overall it's probably still a step in the right direction so 👍

2021-10-14 15:41 UTC, ehigham commented on google/src/main/scala/org/broadinstitute/dsde/rawls/google/GoogleUtilities.scala
> +      case t: HttpResponseException if t.getStatusCode/100 == 4 => t.getStatusCode != 404
I've abcked out of changing all the 404 error handling and just localised it to `getGoogleProject`

2021-10-15 14:59 UTC, marctalbott commented on core/src/main/scala/org/broadinstitute/dsde/rawls/user/UserService.scala
> +    def F = Applicative[Future]
I have some minor reservations about introducing Applicative here. I'm not sure what benefits it provides over an if statement. Is there something I'm missing?

2021-10-15 17:38 UTC, marctalbott approved these changes

2021-10-15 17:57 UTC, ehigham commented on core/src/main/scala/org/broadinstitute/dsde/rawls/user/UserService.scala
> +    def F = Applicative[Future]
In simple cases where we'd have one branch, I agree - `when` might be overkill/conceptual overhead. Here I've got 3 instances where the alternative in the `if` statement is to do nothing. I feel `when` improves readability in these places as it reduces noise and code bloat, especially when combined with effects. Thanks for the shout out on reabability - I'm always happy to have these conversations.

2021-10-15 17:59 UTC, merged