AS-1012: Migrate CDC shard and 3 smallest shards [start of Phase 2]
broadinstitute/rawls pull request #1561
Opened 2021-10-27 18:30 UTC by MatthewBemis

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check that the **Product Owner** has signed off on any user-facing changes
- [ ] **Submitter**: Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Database checks:
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] Tell your tech lead (TL) that the PR exists if they want to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2021-10-27 19:19 UTC, MatthewBemis commented on core/src/main/resources/org/broadinstitute/dsde/rawls/liquibase/changesets/20210924_populate_sharded_entity_tables.xml
> -        <rollback>DROP TABLE IF EXISTS ENTITY_ATTRIBUTE_00_03; call createEntityAttributeShard('00_03');</rollback>
this rollback procedure is no longer valid, since it could end up deleting data that doesn't exist in the `archived` table

2021-10-27 19:21 UTC, MatthewBemis commented on core/src/main/resources/org/broadinstitute/dsde/rawls/liquibase/changesets/20210924_populate_sharded_entity_tables.xml
> +<!--    <changeSet logicalFilePath="dummy" author="davidan" id="populate_shard_00_03">-->
I think a reasonable approach is to just uncomment shards once we want to migrate them

2021-10-27 19:22 UTC, MatthewBemis commented on core/src/main/resources/org/broadinstitute/dsde/rawls/liquibase/changesets/20210924_populate_sharded_entity_tables.xml
>          <sql>call copyRowsToAttributeShard('9c_9f');</sql>
this is the important shard! the other 3 uncommented are the 3 smallest shards (as of 1-2 weeks ago, at least)

2021-10-27 19:33 UTC, davidangb commented on core/src/main/resources/org/broadinstitute/dsde/rawls/liquibase/changesets/20210924_populate_sharded_entity_tables.xml
> +<!--    <changeSet logicalFilePath="dummy" author="davidan" id="populate_shard_00_03">-->
we can't reuse the changeset though - each migration will need to be a new changeset. EDIT: duh, brainfart … these are all individual changesets. Ignore this comment!

2021-10-27 20:19 UTC, davidangb requested changes
A few thoughts:
1. This is missing a critical step of updating the `shard_state` on individual workspaces to `Sharded`. Without that, we just copy the entity attribute rows, but the workspaces will keep using the big table.
2. I think that if we are migrating shards incrementally, we should delete the attribute rows from the big table after we successfully copy them into the shard table. Probably this should happen as part of the same transaction that copies them, so any transaction rollback will cover both operations. I could be swayed into the deletes happening in separate changesets, too - as long as we ensure that the copy operation succeeds before the delete operation runs.

2021-10-27 20:28 UTC, davidangb commented
I wonder if the right approach, to make future migrations easier, is:
1. create a new stored proc that updates all workspaces in a given shard to `Sharded`
2. create a new stored proc that deletes all rows in a given shard from the big attribute table
3. create a new "wrapper" stored proc that calls `copyRowsToAttributeShard`, then the two new procs from 1 and 2, and does all of this inside a single transaction
4. use the "wrapper" stored proc inside the liquibase changesets

2021-10-27 20:35 UTC, MatthewBemis commented
re: 1)....oops duh. quite the oversight.

re: 2) I thought we had decided as part of [the rollback process](https://docs.google.com/document/d/10zECWn-OiKtOgycm8uPChKPR5ABIBrQ8IuQh7Ibr0Us/edit#) that we would not be deleting the rows from the main table until later on? Or was this only the rollback process for Phase 1?

2021-10-27 21:34 UTC, davidangb commented
ah, I thought we hadn't settled on a decision about deleting rows from the main table … I was landing on a decision in this PR thread but I guess you're right! That's fine - though once we get another tranche or two of shards migrated, we might want to reconsider for perf reasons

2021-10-28 19:06 UTC, MatthewBemis commented on core/src/main/resources/org/broadinstitute/dsde/rawls/liquibase/changesets/20210924_sharded_entity_tables.xml
> +                DECLARE exit handler FOR SQLEXCEPTION
this exit handler stuff is a bit unfamiliar to me but based on research seemed like the appropriate way to guarantee that the two underlying `call`s were in the same txn and would be rolled back

2021-10-28 19:24 UTC, MatthewBemis commented on core/src/main/resources/org/broadinstitute/dsde/rawls/liquibase/changesets/20210924_sharded_entity_tables.xml
> +                SET @sql_text:=CONCAT('update WORKSPACE w set shard_state="Sharded" where shardIdentifier(hex(w.id)) = ''',@tableSuffix,''';');
to reviewer: after reading this again i'm double checking this line right now

2021-10-28 19:37 UTC, sagehen03 approved these changes

2021-10-28 19:37 UTC, sagehen03 commented on core/src/main/resources/org/broadinstitute/dsde/rawls/liquibase/changesets/20210924_populate_sharded_entity_tables.xml
> -        <rollback>DROP TABLE IF EXISTS ENTITY_ATTRIBUTE_00_03; call createEntityAttributeShard('00_03');</rollback>
Good catch! Were you thinking about new workspaces starting to populate those sharded tables or something else?

2021-10-28 19:37 UTC, sagehen03 commented on core/src/main/resources/org/broadinstitute/dsde/rawls/liquibase/changesets/20210924_sharded_entity_tables.xml
> +                DECLARE exit handler FOR SQLEXCEPTION
If you've tested this and feel confident in it, then by all means, but my opinion is it's overkill.  The migration will run single threaded when I believe nothing else will be accessing the database so a failure seems unlikely, and I believe copyRowsToAttributeShard is already transactional? So the scenario that I think this new code is guarding against is the workspaces for the shard being migrated but then not updating the migration flag which is a state that's pretty easy to remedy, my .02.

2021-10-28 21:14 UTC, davidangb approved these changes
especially because you told me you tested this a few times against dev clones, I'm :+1:. There's one nit inline about "Sharded" vs "sharded" but I'll proactively approve because that's such a small change!

2021-10-28 21:14 UTC, davidangb commented on core/src/main/resources/org/broadinstitute/dsde/rawls/liquibase/changesets/20210924_sharded_entity_tables.xml
> +    </changeSet>
nit: in Scala, we set new workspaces to a `shard_state` value of `Sharded` (capitalized). Could you make it consistent here? Else we'll end up with `Sharded` for newly-created workspaces and `sharded` for migrated workspaces. I know that Scala's `WorkspaceShardStates.withName` is case-insensitive but this will bug me looking at the db rows :)

2021-10-28 21:14 UTC, davidangb commented on core/src/main/resources/org/broadinstitute/dsde/rawls/liquibase/changesets/20210924_sharded_entity_tables.xml
> +                DECLARE exit handler FOR SQLEXCEPTION
I also think the exception case is unlikely, but this exit handler looks correct to me. Since we'll never actually hit the exit handler I don't mind leaving it in!

2021-10-29 14:25 UTC, MatthewBemis commented on core/src/main/resources/org/broadinstitute/dsde/rawls/liquibase/changesets/20210924_sharded_entity_tables.xml
> +    </changeSet>
Oh ew. We have `unsharded` and `Sharded` in live envs right now too so that's slightly annoying. I'll at least make the sharded state consistent. More motivation to finish the migration so we can drop the column entirely :p

2021-10-29 14:26 UTC, MatthewBemis commented on core/src/main/resources/org/broadinstitute/dsde/rawls/liquibase/changesets/20210924_populate_sharded_entity_tables.xml
> -        <rollback>DROP TABLE IF EXISTS ENTITY_ATTRIBUTE_00_03; call createEntityAttributeShard('00_03');</rollback>
Yup that's exactly it!

2021-11-01 02:58 UTC, MatthewBemis commented
jenkins retest

(seems to be stuck)

2021-11-01 15:22 UTC, merged