QA-2092: Specify an environment in can-i-deploy workflow dispatch
broadinstitute/rawls pull request #2442
Opened 2023-07-12 14:47 UTC by ichengchang

Ticket: <Link to Jira ticket>
<Put notes here to help reviewer understand this PR>

---

**PR checklist**

- [ ] Include the JIRA issue number in the PR description and title
- [ ] Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] If you changed anything in `model/`, then you should [publish a new official `rawls-model`](https://github.com/broadinstitute/rawls/blob/develop/README.md#publish-rawls-model) and update `rawls-model` in [Orchestration's dependencies](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/project/Dependencies.scala).
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green, including CI tests
- [ ] **Squash commits and merge** to develop (branches are automatically deleted after merging)
- [ ] Inform other teams of any substantial changes via Slack and/or email

2023-07-13 14:47 UTC, knapii-developments approved these changes

2023-07-13 14:55 UTC, cahrens requested changes
I would rather that `can-i-deploy` take care of avoiding matrix since we are currently only running on an single environment anyway. Otherwise every workflow that calls `can-i-deploy` would have to make this change, and then remove it when the underlying issue is fixed.

2023-07-14 13:04 UTC, ichengchang commented
@knapii-developments Christina is referring to approving and merging [PR](https://github.com/broadinstitute/terra-github-workflows/pull/84) rather than merging this one because other teams wouldn't have to make the change in their GHA workflow. As Christina said, right now `can-i-deploy` is fixed to `alpha` and the goal is to have an interim solution to address the false positives / negatives arising from matrix strategy.

2024-05-06 19:35 UTC, aherbst-broad commented
Closing this PR as it look stale. Please reopen if I am mistaken.

2024-05-06 19:35 UTC, closed without merging