ID-707 Fix workflow submission notifications for b2c users.
broadinstitute/rawls pull request #2463
Opened 2023-07-26 19:00 UTC by Ghost-in-a-Jar

Ticket: https://broadworkbench.atlassian.net/browse/ID-707

Users with legacy google subject ids are able to receive notifications but not users with only new b2c ids. This pr adds the path to use the b2c id sam returns. In the original registration with thurloe, orchestration uses the [b2c id from the request header as a fallback if the goog subject id isnt present](https://github.com/broadinstitute/firecloud-orchestration/blob/HEAD/src/main/scala/org/broadinstitute/dsde/firecloud/utils/StandardUserInfoDirectives.scala#L21C1-L21C138) to save the thurloe record. So we should follow that same logic here.

Long term we may want to consider migrating all thurloe records to b2c to clean up tech debt, but I see that as out of scope of this support ticket.

---

**PR checklist**

- [ ] Include the JIRA issue number in the PR description and title
- [ ] Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] If you changed anything in `model/`, then you should [publish a new official `rawls-model`](https://github.com/broadinstitute/rawls/blob/develop/README.md#publish-rawls-model) and update `rawls-model` in [Orchestration's dependencies](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/project/Dependencies.scala).
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green, including CI tests
- [ ] **Squash commits and merge** to develop (branches are automatically deleted after merging)
- [ ] Inform other teams of any substantial changes via Slack and/or email

2023-07-27 20:42 UTC, tlangs requested changes

2023-07-27 20:42 UTC, tlangs commented on core/src/main/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionMonitorActor.scala
> +        // Additionally, users are currently being stored in thurloe via their googleSubjectId if present, otherwise their b2cId
the userSubjectId is not the B2C ID, its the Sam User ID

2023-07-27 20:42 UTC, tlangs commented on core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +        // Thurloe needs the google subject id (in the case of gcp user) or the b2c id.
Again, not the B2C ID

2023-07-27 20:42 UTC, tlangs commented on core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +      // Thurloe needs the google subject id (in the case of gcp user) or the b2c id.
Again, not the B2C ID.

2024-05-06 19:35 UTC, aherbst-broad commented
Closing this PR as it appears stale. Please reopen if I am mistaken.

2024-05-06 19:35 UTC, closed without merging