[WOR-1698] Workspace admin support API
broadinstitute/rawls pull request #3046
Opened 2024-09-25 18:45 UTC by marctalbott

Ticket: [WOR-1698](https://broadworkbench.atlassian.net/browse/WOR-1698)
* Add new API `/api/admin/workspaces/{workspaceId}` which returns the workspace details and its settings.
  * I opted not to return the same response as the non-admin `getWorkspace` as that response includes a lot of information about specific user access to the workspace. 
  * One notable omission is the Azure managed app coordinates. We'll need to add a WSM admin API that returns workspace information to fetch the managed app coordinates. Given our current stance on Azure, I felt this wasn't worth implementing right now.

---

**PR checklist**

- [ ] Include the JIRA issue number in the PR description and title
- [ ] Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] If you changed anything in `model/`, then you should [publish a new official `rawls-model`](https://github.com/broadinstitute/rawls/blob/develop/README.md#publish-rawls-model) and update `rawls-model` in [Orchestration's dependencies](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/project/Dependencies.scala).
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green, including CI tests
- [ ] **Squash commits and merge** to develop (branches are automatically deleted after merging)
- [ ] Inform other teams of any substantial changes via Slack and/or email

2024-09-25 19:05 UTC, aherbst-broad approved these changes

2024-09-26 13:00 UTC, blakery requested changes

2024-09-26 13:00 UTC, blakery commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpSamDAO.scala
> +    override def userHasAction(resourceTypeName: SamResourceTypeName,
The name of this should probably indicate that this is for an admin permission (something like: `userHasAdminAction`).

2024-09-26 13:00 UTC, blakery commented on core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceAdminService.scala
> +    samDAO.admin
Why not just put this as part of the `for` comprehension?
```suggestion
    for {
      userIsAdmin <- samDAO.admin.userHasAction(SamResourceTypeNames.workspace, SamResourceTypeAdminActions.readSummaryInformation, ctx)
      _ = if (!userIsAdmin) throw new RawlsExceptionWithErrorReport(
        ErrorReport(StatusCodes.Forbidden, "You must be an admin to call this API.")
      )
      workspaceOpt <- workspaceRepository.getWorkspace(workspaceId)
      workspace = workspaceOpt.getOrElse(throw NoSuchWorkspaceException(workspaceId.toString))
      settings <- workspaceSettingRepository.getWorkspaceSettings(workspaceId)
    } yield WorkspaceAdminResponse(
      WorkspaceDetails.fromWorkspaceAndOptions(workspace, None, useAttributes = false),
       settings
    )
```

2024-09-26 13:00 UTC, blakery commented on core/src/test/scala/org/broadinstitute/dsde/rawls/webservice/AdminApiServiceSpec.scala
> +  it should "get a workspace with its current settings" in {
🥳

2024-09-26 13:00 UTC, blakery commented on core/src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceAdminServiceUnitTests.scala
Super Nit/FYI/note for posterity: `___Spec` is the normal convention for naming test files with scalatest. I just started naming things `___UnitTests` because I needed to put things in separate classes when migrating conventions.

2024-09-26 13:00 UTC, blakery commented on core/src/main/resources/swagger/api-docs.yaml
> +    WorkspaceDetailsWithSettings:
Should this be `WorkspaceAdminResponse`, or `WorkspaceAdminDetailsWithSettings`, or something similar, to match up with the name in `WorkspaceModel`?

2024-09-27 15:20 UTC, marctalbott commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpSamDAO.scala
> +    override def userHasAction(resourceTypeName: SamResourceTypeName,
Yeah, I left it out because it's in the `AdminDao`, but probably doesn't hurt to be extra clear

2024-09-27 15:20 UTC, marctalbott commented on core/src/main/resources/swagger/api-docs.yaml
> +    WorkspaceDetailsWithSettings:
Yes, good catch, just missed it when I renamed the model

2024-09-27 15:20 UTC, marctalbott commented on core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceAdminService.scala
> +    samDAO.admin
No compelling reason, I can switch it

2024-09-27 15:20 UTC, marctalbott commented on core/src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceAdminServiceUnitTests.scala
Yeah, I've just been sticking with `UnitTests` to distinguish the two styles of testing. I don't feel particularly strongly about continuing to do that vs following the normal convention

2024-09-27 20:58 UTC, blakery approved these changes

2024-09-30 22:24 UTC, merged