use pipeline injector on workspacepitest
broadinstitute/rawls pull request #3055
Opened 2024-09-30 19:26 UTC by jyang-broad

Ticket: <Link to Jira ticket>
<Put notes here to help reviewer understand this PR>

---

**PR checklist**

- [ ] Include the JIRA issue number in the PR description and title
- [ ] Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] If you changed anything in `model/`, then you should [publish a new official `rawls-model`](https://github.com/broadinstitute/rawls/blob/develop/README.md#publish-rawls-model) and update `rawls-model` in [Orchestration's dependencies](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/project/Dependencies.scala).
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green, including CI tests
- [ ] **Squash commits and merge** to develop (branches are automatically deleted after merging)
- [ ] Inform other teams of any substantial changes via Slack and/or email

2024-11-18 14:10 UTC, dvoet requested changes

2024-11-18 14:10 UTC, dvoet commented on .github/workflows/rawls-build-tag-publish-and-run-tests.yaml
> +          ref: refs/heads/DDO-3838-test-remove-confs
Is this intentional?

2024-11-18 14:10 UTC, dvoet commented on .github/workflows/rawls-build-tag-publish-and-run-tests.yaml
> +            "bee-name": "juyang-swatomation-vervet",
revert?

2024-11-18 14:10 UTC, dvoet commented on .github/workflows/rawls-build-tag-publish-and-run-tests.yaml
> +    if: false # always() # always run to confirm bee is destroyed
revert?

2024-11-22 22:41 UTC, kevinmarete requested changes
The PR has multiple test failures. Can we fix them or is this PR even still relevant?

2025-04-11 15:58 UTC, closed without merging