Read final output workspace setting at submission time [AN-134]
broadinstitute/rawls pull request #3106
Opened 2024-10-30 13:42 UTC by lucymcnatt

Ticket: [AN-134](https://broadworkbench.atlassian.net/browse/AN-134)

if we see SeparateSubmissionFinalOutputs as true in workspace settings, set:
- `final_workflow_outputs_dir` to `"submissions/final-outputs"`
- `final_workflow_outputs_dir_metadata` to `"destination"` 
- `mode` to `"copy"`. 

---

**PR checklist**

- [ ] Include the JIRA issue number in the PR description and title
- [ ] Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] If you changed anything in `model/`, then you should [publish a new official `rawls-model`](https://github.com/broadinstitute/rawls/blob/develop/README.md#publish-rawls-model) and update `rawls-model` in [Orchestration's dependencies](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/project/Dependencies.scala).
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green, including CI tests
- [ ] **Squash commits and merge** to develop (branches are automatically deleted after merging)
- [ ] Inform other teams of any substantial changes via Slack and/or email

2024-10-30 15:31 UTC, aednichols requested changes
The `final_workflow_outputs_mode` option no longer exists in Cromwell, apologies if there were misleading mentions of it somewhere.

It was replaced by `final_workflow_outputs_dir_metadata`.

2024-10-30 21:46 UTC, aednichols approved these changes
Looks right to me, did not test.

2024-10-30 21:46 UTC, aednichols commented on core/src/main/scala/org/broadinstitute/dsde/rawls/jobexec/WorkflowSubmissionActor.scala
>        // Cromwell `/outputs` endpoint and Terra data table use this location
References to "move" are obsolete, and might as well just use the new ticket number
```suggestion
      // Cromwell `/outputs` endpoint and Terra data table use this location
```

2024-10-31 15:35 UTC, LizBaldo approved these changes
LGTM! I trust Adam completely on the business logic though, I mostly focused on the Scala code itself

2024-10-31 16:14 UTC, aednichols reviewed
This would be good to test on Dev before merging, I can definitely help interpret the workflows behavior.

2024-11-04 18:31 UTC, lucymcnatt commented
@aednichols with the demo from mobbing this morning, are you comfortable with merging?

2024-11-04 18:51 UTC, aednichols commented
Yes! Seeing is believing.

2024-11-04 18:51 UTC, aednichols approved these changes

2024-11-04 18:54 UTC, merged