GAWB-1031: Return workflow status info in listSubmissions endpoint
broadinstitute/rawls pull request #541
Opened 2016-09-26 12:48 UTC by MatthewBemis

-Still needs swagger update
-Still need to do an explain on the query

Generates n extra queries per submission listing, where n is the number of submissions

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Make sure Swagger is updated if API changes
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Database checks:
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell ![](http://i.imgur.com/9dLzbPd.png) that the PR exists if he wants to look at it **(apply requires_doge label)**
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] ![](http://i.imgur.com/9dLzbPd.png) sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2016-09-27 15:12 UTC, dvoet requested changes
The code as written does a query per submission. This can be done instead as 1 query for all submissions. It is possible that this could be added to the starting query but that may be too complicated. If so, it can be a second query.

essentially the second query would be like
select s.id, w.status, count(*)
from submission s join workflow w on s.id = w.submission_id
where s.workspace_id = ?
group by s.id, w.status

2016-09-27 15:12 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/SubmissionComponent.scala
> +      query.result.map(wfs => wfs.groupBy(identity).mapValues(_.size))
this pulls all the workflows into memory then groups and counts, that should all be done in the database

2016-09-27 18:26 UTC, MatthewBemis commented
@dvoet cc97fce reduces number of queries from n<sub>submission</sub> to 1

2016-09-27 20:01 UTC, MatthewBemis commented on src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/SubmissionComponent.scala
> +            val subStatuses = states.getOrElse(submissionRec.id, Seq.empty).map(x => x.workflowStatus -> x.count).toMap
just realized I left a temp variable name "x" in here, i'll fix that tomorrow

2016-09-28 19:17 UTC, dvoet approved these changes
👍

2016-09-28 20:04 UTC, ansingh7115 commented
👍

2016-09-29 12:29 UTC, merged