GAWB-1059: Endpoints for listing workspaces by attribute
broadinstitute/rawls pull request #552
Opened 2016-10-19 18:07 UTC by MattPutnam

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Make sure Swagger is updated if API changes
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Database checks:
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell ![](http://i.imgur.com/9dLzbPd.png) that the PR exists if he wants to look at it **(apply requires_doge label)**
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] ![](http://i.imgur.com/9dLzbPd.png) sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2016-10-19 19:35 UTC, davidangb commented
I don't think rawls should have the list-published endpoint; it should have just the query-by-attribute endpoint. Orchestration has the Library knowledge (see https://github.com/broadinstitute/firecloud-orchestration/blob/develop/src/main/scala/org/broadinstitute/dsde/firecloud/service/LibraryService.scala#L27) ... orchestration can just call the query-by-attribute endpoint, passing the appropriate criteria.

2016-10-19 19:43 UTC, davidangb commented on src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +      dataSource.inTransaction { dataAccess =>
add something along the lines of

```
      if (attributeMap.size != 1)
        throw new RawlsExceptionWithErrorReport(errorReport = ErrorReport(StatusCodes.BadRequest, "specify one attribute only"))
```

here. I think it's reasonable to support only a single attribute for now - and your code lower down only looks for AttributeString, AttributeNumber, AttributeBoolean, so the lower code only supports a single attribute - therefore we should validate the request.

2016-10-19 19:50 UTC, dvoet requested changes
I see you checked the "Database checks" box yet you did not include explain plans.

2016-10-19 19:50 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/AttributeComponent.scala
> +          case b:AttributeBoolean => rec.valueBoolean === b.value
since this does not match all cases you should have a case _ => throw exception

also your cases would be better like
case AttributeString(s) => rec.valueString === s
etc.

2016-10-19 19:50 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/AttributeComponent.scala
> +    def findByNameQuery(attrName: AttributeName): WorkspaceAttributeQueryType = {
why not put these 2 methods in AttributeQuery? Why is it specific to workspaces?

2016-10-19 19:50 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/WorkspaceComponent.scala
> +    def getWorkspacesWithAttribute(attributeMap: AttributeMap) = {
why does this take a map as an input but ignore all but the head? This should take attrName and attrValue as parameters.

2016-10-19 19:50 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/WorkspaceComponent.scala
> +    def listPublished(): ReadAction[Seq[Workspace]] = {
a) I don't think this belongs in rawls at all
b) it certainly does not belong here in the DAO. This is business logic and should be in WorkspaceService. 

This goes for getPublishedWorkspaces too.

2016-10-19 19:50 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
> +  def libraryAttribute(name: String) = AttributeName(libraryNamespace, name)
I would call this withLibraryNS to be consistent with withDefaultNS

2016-10-19 19:50 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +    case ListWorkspacesWithAttribute(attributeMap) => pipe(listWorkspacesWithAttribute(attributeMap)) to sender
The convention is to prefix admin functions with Admin (e.g. AdminListPublishedWorkspaces). Also the asFCAdmin should be up here:
case AdminListPublishedWorkspaces => pipe(asFCAdmin { listPublishedWorkspaces() }) to sender

2016-10-19 19:50 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/rawls/webservice/AdminApiService.scala
> +        entity(as[AttributeMap]) { attributeMap =>
since we only handle a single key/value, this should take a single key/value, not a map. Also, this probably should be a Get not a post.

2016-10-19 19:50 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/rawls/webservice/AdminApiService.scala
> +    path("admin" / "publishedWorkspaces") {
I don't think rawls should have this API. Whoever is calling this should use the admin/workspacesByAttribute api instead.

2016-10-19 19:50 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/AttributeComponent.scala
> +          case b:AttributeBoolean => rec.valueBoolean === b.value
do we care that this will work on lists as well?

2016-10-19 20:08 UTC, MattPutnam commented on src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +    case ListWorkspacesWithAttribute(attributeMap) => pipe(listWorkspacesWithAttribute(attributeMap)) to sender
I was following the pattern of ListAllWorkspaces

2016-10-20 01:43 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +    case ListWorkspacesWithAttribute(attributeMap) => pipe(listWorkspacesWithAttribute(attributeMap)) to sender
older code, older pattern :( if you want to change that one too, be my guest

2016-10-20 01:45 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +      dataSource.inTransaction { dataAccess =>
if we are only supporting size=1, it should not be a map at all, just pass in the key and the value.

2016-10-20 16:45 UTC, davidangb commented on src/main/scala/org/broadinstitute/dsde/rawls/webservice/AdminApiService.scala
> +        entity(as[AttributeMap]) { attributeMap =>
I disagree this should be a GET. The request requires a body, so it should be a POST.

It needs a body so we can distinguish string/numeric/boolean values. We may need to specify a body of:

```
{ "myAttribute" : "123"}
```

which is different from:

```
{ "myAttribute" : 123 }
```

we can't distinguish those if they're in the URL:

```
/api/admin/workspacesByAttribute/myAttribute/123
```

in the url, should `123` be a string or a number?

2016-10-20 17:26 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/rawls/webservice/AdminApiService.scala
> +        entity(as[AttributeMap]) { attributeMap =>
I understand the problem. Semantically, though, this feels like it should be a GET. Also I feel like distinguishing the type in such a subtle way is not a great API. I know it is verbose, but what about query parameters:
attributeName
valueString
valueBoolean
valueNumber

it also seems icky but it is clear what is going on.

Alternately, I would love a way that queried independent of type (i.e. "123" would match the number 123 as well as the string).

2016-10-20 17:44 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/rawls/webservice/AdminApiService.scala
> +      get {
I should have been more specific. I agree that if there is a request body this should be a post. But this feels like it should be a get with query parameters.

2016-10-24 16:58 UTC, MatthewBemis commented on src/test/scala/org/broadinstitute/dsde/rawls/webservice/AdminApiServiceSpec.scala
> +    Get(s"/admin/workspaces?attributeName=number&valueNumber=10", httpJson(Map("number" -> 10))) ~>
the json payload isn't needed anymore now that you're using query params

2016-10-24 17:03 UTC, MatthewBemis commented
One minor comment and an explain plan for WorkspaceComponent.getWorkspacesWithAttribute and you'll have a :+1: from me

2016-10-24 17:30 UTC, davidangb reviewed
this is getting close!

2016-10-24 17:30 UTC, davidangb commented on src/main/scala/org/broadinstitute/dsde/rawls/webservice/AdminApiService.scala
> +        }
for code style, I'd prefer to break this up so the large pattern-match is outside of the call to perRequest():
```
val msg = nameOption match {
  ...
}

perRequest(requestContext,
  WorkspaceService.props(workspaceServiceConstructor, userInfo),
  msg)
```

2016-10-24 17:30 UTC, davidangb commented on src/test/scala/org/broadinstitute/dsde/rawls/webservice/AdminApiServiceSpec.scala
> +        theSameElementsAs(Array(testData.workspace, testData.workspaceNoGroups, testData.workspacePublished))
could you add tests for number and boolean, too?

2016-10-24 17:30 UTC, davidangb commented on src/main/scala/org/broadinstitute/dsde/rawls/webservice/AdminApiService.scala
> +                  case (None, Some(number), None) => WorkspaceService.AdminListWorkspacesWithAttribute(name, AttributeNumber(number.toInt))
why `toInt`? I believe AttributeNumber is backed by a BigDecimal ... so converting to int here could lose precision.

2016-10-25 01:29 UTC, davidangb commented
👍 from me on the latest changes. I still see as outstanding a response to Doug's older comment about methods in workspaceAttributeQuery vs. AttributeQuery (as well as the explain plans)

2016-10-27 16:13 UTC, davidangb commented
Re: the full table scan: of course we want to avoid those. But I don't think we should add an index for this specific PR/endpoint. This endpoint is admin-only, and it will only be used by developers to reset our ES indices. This should not happen too often - though it will happen relatively often during active development. To that end, I don't want to add a db index that will (slightly) affect runtime writes, just to make a developer- and admin- endpoint lighter.

2016-10-28 15:09 UTC, dvoet commented
the reason I vote for an index now is that I suspect we will use this more later and we will forget that there is no index... how will we remember? But I don't care enough to hold back this PR.

2016-10-28 15:10 UTC, dvoet approved these changes
concerned about future need for index but proceed

2016-10-28 15:26 UTC, davidangb commented
I suggest then adding either 1) an index, or 2) comments in the relevant code section(s) to indicate there is no index. (if you add a comment, I do not feel the need to re-review)

2016-10-28 19:01 UTC, merged