GAWB-1275: Convert workspace invites into real access upon registration
broadinstitute/rawls pull request #607
Opened 2017-01-10 16:43 UTC by MatthewBemis

The final piece.

note that this is a PR into https://github.com/broadinstitute/rawls/pull/572

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check that the **Product Owner** has signed off on any user-facing changes
- [ ] **Submitter**: Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Database checks:
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell your tech lead (TL) that the PR exists if they want to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-01-11 15:30 UTC, dvoet requested changes

2017-01-11 15:30 UTC, dvoet commented on core/src/main/scala/org/broadinstitute/dsde/rawls/user/UserService.scala
> +    val groupRefs = dataSource.inTransaction { dataAccess =>
Getting the access group refs can be done in 1 query. This implementation does 1 query to find, 1 each to load access group. It is not a big deal here but we should be in the mindset of doing things in bulk in the database.

Maybe a rule of thumb should be if you use DBIO.sequence, look for a better way.

2017-01-11 15:30 UTC, dvoet commented on core/src/test/scala/org/broadinstitute/dsde/rawls/webservice/UserApiServiceSpec.scala
> +
test that the invite has been deleted and more than one invite

2017-01-11 18:26 UTC, MatthewBemis commented
@dvoet back to you. I updated the test but left the query the way it was, as we talked about.

2017-01-12 16:57 UTC, dvoet approved these changes

2017-01-13 19:13 UTC, breilly2 approved these changes

2017-01-17 13:14 UTC, merged