Fix create project polling
broadinstitute/rawls pull request #618
Opened 2017-02-01 01:30 UTC by dvoet

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check that the **Product Owner** has signed off on any user-facing changes
- [ ] **Submitter**: Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Database checks:
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell your tech lead (TL) that the PR exists if they want to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-02-03 19:09 UTC, breilly2 requested changes
Overall, this looks like what I would expect based on my knowledge of the problem. I'm guessing that there might be other Google operations beyond billing projects that we might want some of this. I could even imagine this generalized to a system-wide event bus that could be used to orchestrate long-running processes with hooks for providing feedback in the UI, but that can be for a later time.

2017-02-03 19:09 UTC, breilly2 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpGoogleServicesDAO.scala
> +    // this code is a colossal DRY violation but because the operations collection is different
You might be able to be more DRY by using higher-order functions but I'm not sure it would be any more readable, especially with this comment being here. This is well contained and explained with comments. :+1:

2017-02-03 19:09 UTC, breilly2 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpGoogleServicesDAO.scala
> +      if (toScalaBool(googleOperation.getDone) && Option(googleOperation.getError).map(_.getCode == GoogleRpcErrorCodes.ALREADY_EXISTS).getOrElse(false)) {
IntelliJ says, "Replace map and getOrElse(false) with exists" which yields:

`Option(googleOperation.getError).exists(_.getCode == GoogleRpcErrorCodes.ALREADY_EXISTS)`

Other the the overloading of "exists" (which is only a little confusing to me due to still getting used to `Option`), I think this reads nicely.

2017-02-03 19:09 UTC, breilly2 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpGoogleServicesDAO.scala
> +  override def completeProjectSetup(project: RawlsBillingProject): Future[Try[Unit]] = {
It's unclear to me what the division is between `beginProjectSetup` and `completeProjectSetup` such that, if I were to add something, I wouldn't be sure where it should happen. Could you add some docs to explain the difference?

2017-02-06 18:27 UTC, dvoet commented
@breilly2 ready for re-review

2017-02-06 18:54 UTC, breilly2 approved these changes
Added comments are perfect, and I appreciate the added test for creating workspaces projects that aren't ready. Suggestion for the future: should the UI not allow a user to choose a project that isn't ready?

2017-02-06 20:09 UTC, dvoet commented
seems like the UI already does not allow selection of Creating project, need it to filter out Error as well.

2017-02-16 14:25 UTC, merged