GAWB-1139: Enable Job Avoidance
broadinstitute/rawls pull request #623
Opened 2017-02-03 16:11 UTC by ansingh7115

DO NOT REVIEW

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check that the **Product Owner** has signed off on any user-facing changes
- [ ] **Submitter**: Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Database checks:
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell your tech lead (TL) that the PR exists if they want to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-02-03 16:47 UTC, helgridly requested changes

2017-02-03 16:47 UTC, helgridly commented on core/src/main/resources/swagger/rawls.yaml
> +        description: Whether or not to read from cache for this submission
Nitpick: I'd say "read from *call* cache" here, to be more specific. (This may be a running theme in the review...)

2017-02-03 16:47 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +            evaluator.evalFinalAttribute(workspaceContext, expression).asTry map { tryValuesByEntity =>
note to reviewers: this is just a whitespace change. it goes away with ?w=1 but then you can't add comments :(

2017-02-03 16:47 UTC, helgridly commented on core/src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSpec.scala
> +    val submissionRq = SubmissionRequest("dsde", "NotAllSamplesMethodConfig", "Individual", "indiv1", Some("this.sset.samples"), true)
Why are some of these true and some false?

2017-02-03 18:06 UTC, ansingh7115 commented on core/src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSpec.scala
> +    val submissionRq = SubmissionRequest("dsde", "NotAllSamplesMethodConfig", "Individual", "indiv1", Some("this.sset.samples"), true)
I just randomly chose

2017-02-03 18:17 UTC, helgridly commented on core/src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSpec.scala
> +    val submissionRq = SubmissionRequest("dsde", "NotAllSamplesMethodConfig", "Individual", "indiv1", Some("this.sset.samples"), true)
! Leave them all false and then - if it makes sense to do so - do some testing specifically for when it's true.

2017-02-06 14:41 UTC, dvoet commented on core/src/main/resources/swagger/rawls.yaml
> +        description: Whether or not to read from cache for this submission
I would not use the word "read" because it can also be interpreted as past tense. How about "use" instead.

2017-03-15 21:14 UTC, helgridly approved these changes

2017-03-16 23:09 UTC, merged