send notifications from rawls
broadinstitute/rawls pull request #638
Opened 2017-03-03 15:51 UTC by dvoet

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check that the **Product Owner** has signed off on any user-facing changes
- [ ] **Submitter**: Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Database checks:
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell your tech lead (TL) that the PR exists if they want to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-03-06 18:01 UTC, MatthewBemis commented on core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +          val invitedNotifications = dedupedInvites.map(invite => Notifications.WorkspaceInvitedNotification(invite.email, userInfo.userEmail))
i think we need to do another round of filtering here before we actually get to the list of invite emails that we want to send. basically, if someone updates the `accessLevel` of a pending invite, we don't want to send them another invite to FireCloud

`dedupedInvites` filters out any invites that are identical to ones that already exist, but we still need to do something like: https://github.com/broadinstitute/rawls/pull/638/files#diff-91fe8efb10dfe91234a26e4f80039fc6R525

2017-03-06 18:11 UTC, MatthewBemis requested changes

2017-03-06 18:11 UTC, MatthewBemis commented on core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +          val invitedNotifications = dedupedInvites.map(invite => Notifications.WorkspaceInvitedNotification(invite.email, userInfo.userEmail))
i think we need to do another round of filtering here before we actually get to the list of invite emails that we want to send. basically, if someone updates the `accessLevel` of a pending invite, we don't want to send them another invite to FireCloud

`dedupedInvites` filters out any invites that are identical to ones that already exist, but we still need to do something like: https://github.com/broadinstitute/rawls/pull/638/files#diff-91fe8efb10dfe91234a26e4f80039fc6R525

2017-03-06 18:11 UTC, MatthewBemis commented on project/Version.scala
> -    def getLastModelCommitFromGit = { s"""git log -n 1 --pretty=format:%h ${baseDir.getAbsolutePath}""" !! }
can you give a 1-2 sentence explanation to me about what these changes are and why they're needed?

2017-03-06 19:33 UTC, dvoet commented on project/Version.scala
> -    def getLastModelCommitFromGit = { s"""git log -n 1 --pretty=format:%h ${baseDir.getAbsolutePath}""" !! }
With the old code, each of rawls-utils, workbench-google, workbench-util would get published with different git hashes (the hash of the last change in the subdir). I found it too confusing. Now they all get pushed with the same hash.

2017-03-07 16:27 UTC, MatthewBemis approved these changes
:+1:

2017-03-07 17:58 UTC, merged