Entity Delete GAWB-1666
broadinstitute/rawls pull request #644
Opened 2017-03-10 21:53 UTC by jmthibault79

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check that the **Product Owner** has signed off on any user-facing changes
- [ ] **Submitter**: Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Database checks:
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell your tech lead (TL) that the PR exists if they want to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-03-10 21:54 UTC, jmthibault79 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/DriverComponent.scala
> +    name + "_" + DateTime.now().toString("yyyy-MM-dd_HH.mm.ss")
Can't use colons here because of `AttributeName`s which use colon delimiters

2017-03-10 21:55 UTC, jmthibault79 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/WorkspaceComponent.scala
> -import slick.dbio.Effect.Read
I can revert this file change if you like, since I didn't make a functional change here

2017-03-10 21:58 UTC, jmthibault79 commented on core/src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/AttributeComponentSpec.scala
> +    assertExpectedRecords(WorkspaceAttributeRecord(dummyId2, workspaceId, AttributeName.defaultNamespace, "test", Option("test"), None, None, None, None, None, None, false))
This file has only changes like this

2017-03-10 21:59 UTC, jmthibault79 commented on core/src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponentSpec.scala
> -  it should "get entity types" in withDefaultTestDatabase {
`getEntityTypes()` was not used, so I removed it

2017-03-10 22:01 UTC, jmthibault79 commented on core/src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponentSpec.scala
> +      assertResult(Map("PairSet" -> 1, "Individual" -> 2, "Aliquot" -> 2, "SampleSet" -> 5, "Pair" -> 2)) {
Same as line 86, minus Samples

2017-03-10 22:02 UTC, jmthibault79 commented on core/src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/TestDriverComponent.scala
> -    val extraSample = Entity("extraSample", "Sample", Map.empty)
not used anywhere

2017-03-10 22:03 UTC, jmthibault79 commented on core/src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSpec.scala
> +  it should "continue to monitor a Submission on a deleted entity" in withWorkspaceServiceMockExecution { mockExecSvc => workspaceService =>
Submissions refer to Entities by ID, which will continue to reference the same DB record

2017-03-10 22:14 UTC, jmthibault79 commented on core/src/test/scala/org/broadinstitute/dsde/rawls/webservice/EntityApiServiceSpec.scala
> -  ignore should "*DISABLED* return 204 on entity delete" in withTestDataApiServices { services =>
These basic deleted tests have been moved upward in this file.  These changes are new tests.

2017-03-10 22:16 UTC, jmthibault79 commented on core/src/test/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiServiceSpec.scala
> -    //this endpoint is only temporarily returning MethodNotAllowed. When GAWB-422 is complete, it should return NotFound
This isn't a necessary part of this test

2017-03-13 15:55 UTC, jmthibault79 commented
Discussed FISMA with DevOps and Comms - will have to make a note in the user docs

2017-03-13 17:00 UTC, jmthibault79 commented
TODO:
- update AC in JIRA
- test in FIAB
- Orch Swagger

2017-03-13 17:45 UTC, ansingh7115 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/WorkspaceComponent.scala
> -import slick.dbio.Effect.Read
Yes

2017-03-13 17:52 UTC, ansingh7115 commented on core/src/main/resources/swagger/rawls.yaml
> +    post:
Why is this a post and not a delete?

2017-03-13 18:26 UTC, ansingh7115 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponent.scala
> +      filter(entRec => entRec.workspaceId === workspaceId && ! entRec.deleted)
Maybe rename findEntityByType to findActiveEntityByType or something like that? (same for findEntityByWorkspace)

2017-03-13 18:27 UTC, ansingh7115 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponent.scala
> +    // includes "deleted" hidden entities when using their hidden names
Yay for all these comments!

2017-03-13 18:55 UTC, ansingh7115 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/MethodConfigurationComponent.scala
> +        .update(true, renameForHiding(methodConfigName))
Excellent!

2017-03-13 20:16 UTC, helgridly requested changes
this is really impressive! mostly a few nitpicks / questions

2017-03-13 20:16 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/AttributeComponent.scala
> +      createRecord(0, ownerId, attributeName.namespace, attributeName.name, None, None, None, None, None, None, Option(0), false)
are these ever used to update a record that's already been deleted?

2017-03-13 20:16 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/DriverComponent.scala
> +    name + "_" + DateTime.now().toString("yyyy-MM-dd_HH.mm.ss")
can you and @ansingh7115 sync to genericise "gimme the timestamped version of this thing"?

2017-03-13 20:16 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponent.scala
> +      filter(entRec => entRec.workspaceId === workspaceId && ! entRec.deleted)
yeah, i was wondering this as well. some way to distinguish between the fns that do and don't retried deleteds

2017-03-13 20:16 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponent.scala
> +      DBIO.sequence(batchActions).map(_.reduce(_ ++ _)).flatMap { refIds =>
this... reduces all the results from the batches into a single list, rather than a list-of-lists?

2017-03-13 20:16 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +          dataAccess.entityQuery.getAllReferringEntities(workspaceContext, entRefs.toSet) flatMap { referringEntities =>
can all of this move to a *Component somewhere? it feels a bit too databasey for a *Service

2017-03-13 20:16 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +      if (failures.size == entityTries.size) {
i think you can reasonably merge this block with the one below, and return the full list in the case where none of them can be found

2017-03-13 20:16 UTC, helgridly commented on core/src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponentSpec.scala
> +    assertResult(false) { runAndWait(entityQuery.hide(workspaceContext, "type", "name")) }
now this is switched to hide, we need tests to make sure that actual-delete actually deletes

2017-03-13 20:16 UTC, helgridly commented on core/src/test/scala/org/broadinstitute/dsde/rawls/webservice/EntityApiServiceSpec.scala
> +  it should "return 200 on get deleted entity accessed by its hidden name" in withTestDataApiServices { services =>
what's this used for in practise? historical submissions?

2017-03-13 22:31 UTC, jmthibault79 commented
Hold on... my FIAB testing shows this to be quite broken.

2017-03-13 22:32 UTC, jmthibault79 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/DriverComponent.scala
> +    name + "_" + DateTime.now().toString("yyyy-MM-dd_HH.mm.ss")
Yes we agreed on this representation

2017-03-13 22:33 UTC, jmthibault79 commented on core/src/main/resources/swagger/rawls.yaml
> +    post:
So it can take a JSON payload

2017-03-13 22:37 UTC, jmthibault79 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +      if (failures.size == entityTries.size) {
This division was suggested by Alex.  I'm good with either way.  We can chat.

2017-03-13 22:39 UTC, jmthibault79 commented on core/src/test/scala/org/broadinstitute/dsde/rawls/webservice/EntityApiServiceSpec.scala
> +  it should "return 200 on get deleted entity accessed by its hidden name" in withTestDataApiServices { services =>
That was my thought: enable click-navigation of deleted Entities via their Submissions

2017-03-14 02:58 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponent.scala
> +      entityAttrRec <- entityAttributeQuery if entityAttrRec.ownerId === entityId && ! entityAttrRec.deleted
this looks fishy. if thing == other thing and [bool value]?

2017-03-14 03:01 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponent.scala
> +      entityAttrRec <- entityAttributeQuery if entityAttrRec.ownerId === entityId && ! entityAttrRec.deleted
is this your bug? this is either hard to read or it's a bit funny. shouldn't there be a filter in here? `entityAttributeQuery.filter( _.entity_id == entityId )` or something? where is `entityAttrRec` coming from on the RHS here?

2017-03-14 20:13 UTC, jmthibault79 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponent.scala
> +      entityAttrRec <- entityAttributeQuery if entityAttrRec.ownerId === entityId && ! entityAttrRec.deleted
`entityAttrRec` works like a function parameter here, so this should be equivalent to `entityAttributeQuery.filter(_.owner_id === entityId).filterNot(_.deleted)`

2017-03-14 21:18 UTC, jmthibault79 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/WorkspaceComponent.scala
> -import slick.dbio.Effect.Read
ok

2017-03-14 21:52 UTC, jmthibault79 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponent.scala
> +      filter(entRec => entRec.workspaceId === workspaceId && ! entRec.deleted)
I agree that this is necessary, but I'd prefer to do that as part of a bigger EntityComponent refactoring: https://broadinstitute.atlassian.net/browse/GAWB-1768

2017-03-14 22:04 UTC, jmthibault79 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponent.scala
> +      DBIO.sequence(batchActions).map(_.reduce(_ ++ _)).flatMap { refIds =>
Yes... which is the same as flatten, so I'll change it to flatten for clarity.

2017-03-14 22:22 UTC, jmthibault79 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +          dataAccess.entityQuery.getAllReferringEntities(workspaceContext, entRefs.toSet) flatMap { referringEntities =>
counterpoint: Components don't know about PerRequest.  This doesn't seem out of line with the rest of WorkspaceService to me

2017-03-14 23:13 UTC, jmthibault79 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/AttributeComponent.scala
> +      createRecord(0, ownerId, attributeName.namespace, attributeName.name, None, None, None, None, None, None, Option(0), false)
Good point.  I will need to investigate that some more.

2017-03-16 17:08 UTC, jmthibault79 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +          dataAccess.entityQuery.getAllReferringEntities(workspaceContext, entRefs.toSet) flatMap { referringEntities =>
The "refactor EntityComponent.hide()" commit makes this less databasey.

2017-03-16 17:09 UTC, jmthibault79 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponent.scala
> +      entityAttrRec <- entityAttributeQuery if entityAttrRec.ownerId === entityId && ! entityAttrRec.deleted
This was not the bug.

2017-03-16 17:11 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponent.scala
> +      entityAttrRec <- entityAttributeQuery if entityAttrRec.ownerId === entityId && ! entityAttrRec.deleted
TIL. I find this syntax weird but I'll deal with it.

2017-03-16 17:11 UTC, jmthibault79 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponent.scala
> +      entityAttributeQuery.filter(_.id === attrRec.id).map(rec => (rec.deleted, rec.name)).update(true, renameForHiding(attrRec.name))
The bug was here: I was filtering on attribute name.  So hiding an entity with a "normal" attribute would hide ALL entities' "normal" attributes.  Haha, oops.

2017-03-16 17:13 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponent.scala
> +      entityAttributeQuery.filter(_.id === attrRec.id).map(rec => (rec.deleted, rec.name)).update(true, renameForHiding(attrRec.name))
I assume the tests you added to discover this do a good job of checking for such issues in the future?

2017-03-16 17:28 UTC, jmthibault79 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/AttributeComponent.scala
> +      createRecord(0, ownerId, attributeName.namespace, attributeName.name, None, None, None, None, None, None, Option(0), false)
Good news everyone: they are not

2017-03-16 18:23 UTC, jmthibault79 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponent.scala
> +      entityAttributeQuery.filter(_.id === attrRec.id).map(rec => (rec.deleted, rec.name)).update(true, renameForHiding(attrRec.name))
The last test in EntityComponentSpec (the one with Bob) reproduces the problem, and the added test calls to `countEntitiesAttrs` are intended to confirm that the state of the world is sane.

2017-03-16 20:06 UTC, jmthibault79 commented
Orchestration PR at https://github.com/broadinstitute/firecloud-orchestration/pull/403

Addressed comments except for https://github.com/broadinstitute/rawls/pull/644/files#r105736254 and https://github.com/broadinstitute/rawls/pull/644/files#r105758751.  Do you want to discuss these further?  Ready for re-review.

2017-03-20 14:56 UTC, jmthibault79 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +      if (failures.size == entityTries.size) {
@helgridly we're OK with collapsing these two cases.  400 or 404?

2017-03-20 19:02 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponent.scala
> +      filter(entRec => entRec.workspaceId === workspaceId && ! entRec.deleted)
If you advocate to get said ticket prio'd soon then I'm fine with that.

2017-03-20 19:08 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +      if (failures.size == entityTries.size) {
@breilly2 has convinced me that 400 is the right answer, because 404 implies the resource defined by the URL has not been found.

2017-03-20 19:08 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponent.scala
> +      entityAttributeQuery.filter(_.id === attrRec.id).map(rec => (rec.deleted, rec.name)).update(true, renameForHiding(attrRec.name))
Great, thanks.

2017-03-20 19:10 UTC, helgridly approved these changes
👍 pending 404 collapse. Go ahead and merge once that's done and you're happy.

2017-03-20 19:11 UTC, helgridly commented
(though Travis is currently compile-erroring)

2017-03-20 19:12 UTC, jmthibault79 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/EntityComponent.scala
> +      filter(entRec => entRec.workspaceId === workspaceId && ! entRec.deleted)
Can do

2017-03-20 21:44 UTC, merged