GAWB-1604: Request Group Access
broadinstitute/rawls pull request #695
Opened 2017-05-11 12:43 UTC by MatthewBemis

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check that the **Product Owner** has signed off on any user-facing changes
- [ ] **Submitter**: Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Database checks:
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] Tell your tech lead (TL) that the PR exists if they want to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-05-11 19:08 UTC, dvoet commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/ManagedGroupComponent.scala
> +        authDomains.flatMap { authDomain =>
collect instead of flatMap? Then you can drop `case None => None` I think.

2017-05-11 19:10 UTC, dvoet commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/ManagedGroupComponent.scala
> +      val authDomainQuery: ReadAction[Seq[ManagedGroupRecord]] = managedGroupQuery.filter(_.membersGroupName inSetBind groupList.map(_.membersGroupName.value)).result
use managedGroup instead of authDomain

2017-05-11 19:16 UTC, dvoet commented on core/src/main/scala/org/broadinstitute/dsde/rawls/user/UserService.scala
> +          throw new RawlsExceptionWithErrorReport(ErrorReport(StatusCodes.NotFound, s"The admins of the group ${groupRef.membersGroupName.value} were not found"))
isn't is that the group is not found? Where do we validate that there are not special access instructions, i.e. calling this api is not valid for this group?

2017-05-11 19:16 UTC, rtitle commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/ManagedGroupComponent.scala
> +        authDomains.flatMap { authDomain =>
for-comprehension might work too:
```
authDomainQuery.map { authDomains =>
  for {
    authDomain <- authDomains
    instructions <- authDomain.accessInstructions
  } yield ManagedGroupAccessInstructions(authDomain.membersGroupName, instructions)
}
```

2017-05-11 19:16 UTC, dvoet commented on core/src/main/scala/org/broadinstitute/dsde/rawls/user/UserService.scala
> +        case 0 => RequestComplete(StatusCodes.BadRequest, "We were unable to update the access instructions")
why is this a user error (BadRequest)?

2017-05-11 19:27 UTC, dvoet requested changes
see inline comments

2017-05-11 19:40 UTC, rtitle commented on core/src/main/scala/org/broadinstitute/dsde/rawls/user/UserService.scala
> +      dataAccess.managedGroupQuery.load(groupRef).flatMap {
Minor nitpick: you could probably remove this outer `flatMap` with a `map` like so:
```
dataAccess.managedGroupQuery.load(groupRef).map {
  case None => // throw exception
  case Some(managedGroup) => {
    dataAccess.rawlsGroupQuery.flattenGroupMembership(managedGroup.adminsGroup).map { users =>
      users.foreach { user =>
        notificationDAO.fireAndForgetNotification(GroupAccessRequestNotification(user.userSubjectId.value, groupRef.membersGroupName.value, managedGroup.adminsGroup.groupEmail.value, userInfo.userEmail))
      }
    }
    RequestComplete(StatusCodes.NoContent)
  }
}
```
Not a big deal but IMO makes it a little more clear that the call to `flattenGroupMembership` doesn't influence the return value.

2017-05-11 19:51 UTC, rtitle commented on core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +        val accessGroups = DBIO.sequence(workspaceContext.workspace.accessLevels.values.map { ref =>
It's be nice if `DBIO` had `traverse` since `sequence (xs map f)` == `traverse(xs, f)`. But it doesn't, oh well

2017-05-16 17:23 UTC, dvoet approved these changes

2017-05-16 19:33 UTC, dmohs approved these changes

2017-05-16 19:33 UTC, dmohs commented on core/src/main/resources/swagger/rawls.yaml
> +
https://broadinstitute.atlassian.net/browse/GAWB-1911

2017-05-19 18:18 UTC, merged