GAWB-1690: Support multi-group auth domains
broadinstitute/rawls pull request #733
Opened 2017-07-17 17:28 UTC by MatthewBemis

**Do not merge.**

I'm still in the process of writing a bunch of tests for new scenarios, but the code should be in a reviewable state.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check that the **Product Owner** has signed off on any user-facing changes
- [ ] **Submitter**: Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Database checks:
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] Tell your tech lead (TL) that the PR exists if they want to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-07-17 17:31 UTC, MatthewBemis commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/WorkspaceComponent.scala
> +        DBIO.sequence(groupsToIntersect)
Disclaimer: I'd like to re-write this part to be a bit more efficient

2017-07-18 14:41 UTC, MatthewBemis commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/RawlsGroupComponent.scala
> +      val flattenedGroups = DBIO.sequence(groups.map(flattenGroupMembership).toSeq)
I added a DBIO.sequence here, but it's arguably no worse than what was already here (it was just hardcoded to only handle 2 groups)

Question: Worth the effort to investigate how to do this in batch?

2017-07-18 18:57 UTC, dvoet commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/RawlsGroupComponent.scala
> +      val flattenedGroups = DBIO.sequence(groups.map(flattenGroupMembership).toSeq)
this will be different in sam so leave it alone

2017-07-18 18:57 UTC, UrsaStutsman commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/RawlsGroupComponent.scala
> +      val flattenedGroups = DBIO.sequence(groups.map(flattenGroupMembership).toSeq)
I don't know the answer to this - but am definitely interested in the answer.

2017-07-18 18:57 UTC, UrsaStutsman commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/WorkspaceComponent.scala
> +      } yield authDomainRecord.groupName
Probably just me not remembering something about scala - but what happens here if the if-clause is not met?

2017-07-18 18:57 UTC, UrsaStutsman commented on core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +      val errorMsg = s"Source workspace ${sourceWorkspaceContext.workspace.briefName} has an Authorization Domain containing the groups $missingGroups which, which are missing on the destination work
Think there's a typo in this error message. I believe it should read "...containing the groups $missingGroups, which are missing..." (in other words, just delete the first "which")

2017-07-18 18:57 UTC, UrsaStutsman commented on core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +      val errorMsg = s"Source workspace ${sourceWorkspaceContext.workspace.briefName} has an Authorization Domain containing the groups $missingGroups which, which are missing on the destination work
same typo as above (remove first "which")

2017-07-18 18:57 UTC, UrsaStutsman commented on core/src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/MockGoogleServicesDAO.scala
> +      RawlsGroup(RawlsGroupName(s"${workspaceId}-${accessLevel.toString}"), RawlsGroupEmail(s"$accessLevel@$workspaceId"), users, Set.empty)
More a question than even a comment - but the reason for the "fc" here when we used it previously? And the reason we don't need/want it now? Ok if there are no real answers to this (ie - we don't know - and don't care). Just curious if there's any deeper thought here...

2017-07-18 19:10 UTC, MatthewBemis commented on core/src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/MockGoogleServicesDAO.scala
> +      RawlsGroup(RawlsGroupName(s"${workspaceId}-${accessLevel.toString}"), RawlsGroupEmail(s"$accessLevel@$workspaceId"), users, Set.empty)
it was the incorrect format before. it had no negative side effects in the tests but i wanted to make the behavior of the mock match what's done in HttpGoogleServicesDAO

2017-07-18 19:10 UTC, MatthewBemis commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/RawlsGroupComponent.scala
> +      val flattenedGroups = DBIO.sequence(groups.map(flattenGroupMembership).toSeq)
👍

2017-07-20 02:38 UTC, dvoet requested changes
are there any tests that demonstrate copying and associated AD checks?

2017-07-20 02:38 UTC, dvoet commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/RawlsGroupComponent.scala
> +      flattenedGroups.map(groupUsers => groupUsers.tail.fold(groupUsers.head){(group1, group2) => group1.intersect(group2)})
```groupUsers.reduce(_ intersect _)``` instead of fold

2017-07-20 02:38 UTC, dvoet commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/WorkspaceComponent.scala
> +      } yield authDomainRecord.groupName
in this case the if statement adds a condition to the join in the db query

2017-07-20 02:38 UTC, dvoet commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/WorkspaceComponent.scala
> +        DBIO.sequence(groupsToIntersect)
yes. the current code does an extra query for every workspace to get all the other groups of the intersection. Instead you can do a single query for all of them at once in the outer for comprehension. Probably something similar to how accessGroupRecs are loaded.

I would strive to have all your queries done in the outer for comprehension.

2017-07-20 02:38 UTC, dvoet commented on core/src/main/scala/org/broadinstitute/dsde/rawls/user/UserService.scala
> +        target -> flattenedGroupsToIntersect.tail.values.fold(flattenedGroupsToIntersect.head._2) { (group1, group2) =>
reduce here again I think. Reduce is a special case of fold where the starting value is the first element and the result is of the same type as the collection elements.

2017-07-20 02:38 UTC, dvoet commented on core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +            withClonedAuthDomain(sourceWorkspaceContext, destWorkspaceRequest) { newAuthDomain =>
name misleading here, should be withClonedAuthDomains (plural) and newAuthDomains

2017-07-20 02:38 UTC, dvoet commented on model/src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
> +                      authorizationDomain: Set[ManagedGroupRef],
plural

2017-07-20 02:38 UTC, dvoet commented on model/src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
> +                              authorizationDomain: Set[ManagedGroupRef],
plural

2017-07-20 12:40 UTC, MatthewBemis commented on model/src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
> +                      authorizationDomain: Set[ManagedGroupRef],
there was a discussion in the project team slack room a little while ago about having the authorizationDomain be one thing that can contain between 0 and n groups. see https://broadinstitute.slack.com/archives/G3EJQNF17/p1499264371830532

2017-07-20 13:41 UTC, MatthewBemis commented
@dvoet re: tests for copying entities- there is this: https://github.com/broadinstitute/rawls/pull/733/files#diff-4c66043c9521cd2ac6971f64a7ee521dR1637

2017-07-20 13:44 UTC, dvoet commented on model/src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
> +                      authorizationDomain: Set[ManagedGroupRef],
I find this makes the code confusing. We could have an AD object that contains a set of groups but I don't really like that either... until there are more attributes on the AD.

2017-07-20 13:47 UTC, dvoet commented on core/src/test/scala/org/broadinstitute/dsde/rawls/webservice/EntityApiServiceSpec.scala
> +  it should "return 422 when copying entities from an auth domain protected workspace with only a partial match of AD groups" in withTestDataApiServices { services =>
test for success also

2017-07-28 14:47 UTC, dvoet approved these changes

2017-07-28 19:38 UTC, merged