GAWB-2369: enable empty output expressions
broadinstitute/rawls pull request #759
Opened 2017-08-15 19:47 UTC by jmthibault79

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check that the **Product Owner** has signed off on any user-facing changes
- [ ] **Submitter**: Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Database checks:
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] Tell your tech lead (TL) that the PR exists if they want to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-08-15 20:07 UTC, ansingh7115 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/expressions/OutputExpression.scala
I like this idea

2017-08-16 14:23 UTC, ansingh7115 commented
Code 👍 
Testing it on FIAB now

2017-08-16 15:29 UTC, ansingh7115 commented
Tested on FIAB - used a method config with two outputs - one was left blank while the other wrote back to the data table on the first run and then to the workspace attributes on the second run. The submission ran and succeeded, with the outputs getting written back as expected.

2017-08-16 15:40 UTC, helgridly requested changes
i reeeeally like this approach -- it's tons clearer. buncha thoughts on the line between `Target`s and `OutputExpression`s but otherwise minor nitpicks

2017-08-16 15:40 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/expressions/OutputExpression.scala
> +case class BoundOutputExpression(target: OutputExpressionTarget, attributeName: AttributeName, attribute: Attribute) extends OutputExpression
If I understand correctly: this represents `this.foo = 2`, where `target` is `this`, `attributeName` is `foo`, and `attribute` is `2`?

I suggest renaming `OutputExpressionTarget.prefix` to `root` and possibly `attribute` to `value` or somesuch.

I think the `remainder` function should live in a companion object of `BoundOutputExpression`, at which point you could call it `stripTarget` or `generateAttributeName` or something. There's something weird to me about passing an expression to a target you just generated in order to strip the target off the expression. It's both redundant and feels error-prone (what if you accidentally pass a `this.` expression to a `WorkspaceTarget`?).

2017-08-16 15:40 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionMonitorActor.scala
> +        val boundExpressions = parsedExpressions.collect { case Success(boe @ BoundOutputExpression(target, name, attr)) => boe }
nice

2017-08-16 15:40 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionMonitorActor.scala
> +  def updateEntityAndWorkspace(entity: Entity, workspace: Workspace, workflowOutputs: Iterable[BoundOutputExpression]): (Option[Entity], Option[Workspace]) = {
oh yeah this is delicious

2017-08-16 15:40 UTC, helgridly commented on core/src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionMonitorSpec.scala
> +    parsedExpr shouldBe a[BoundOutputExpression]
worst nitpick ever: space between `a [BoundOutputExpression]`

2017-08-16 15:40 UTC, helgridly commented on core/src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionMonitorSpec.scala
> +    parsedExpr shouldBe a[BoundOutputExpression]
(if scalatest doesn't throw an inexplicable error, which it might)

2017-08-16 16:44 UTC, jmthibault79 commented on core/src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionMonitorSpec.scala
> +    parsedExpr shouldBe a[BoundOutputExpression]
ok sure

2017-08-16 17:39 UTC, jmthibault79 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/expressions/OutputExpression.scala
> +case class BoundOutputExpression(target: OutputExpressionTarget, attributeName: AttributeName, attribute: Attribute) extends OutputExpression
Updated prefix -> root and changed the parsing location.

`(AttributeName, Attribute)` is consistent with how it's used all over Rawls so I'm keeping those names

2017-08-16 17:59 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/expressions/OutputExpression.scala
> +    parseResult.get
`BoundOutputExpression("blarg.blorg", AttributeNumber(2))` will throw an exception, no? which you catch in SMA line 350 by wrapping it in a `Try {}` block, but that's a burden on the caller. perhaps make this more explicit by replacing your `apply` functions with an explict `OutputExpression.from(): Try[OutputExpression]`. it'd be ok to call `get` on that in SMA but that way other people don't get surprised by exceptions

2017-08-16 18:37 UTC, jmthibault79 commented on core/src/main/scala/org/broadinstitute/dsde/rawls/expressions/OutputExpression.scala
> +    parseResult.get
ok here we go

2017-08-16 18:38 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/expressions/OutputExpression.scala
> +    tryParse(ThisEntityTarget, expr, attribute) recoverWith { case _ => tryParse(WorkspaceTarget, expr, attribute) }
@rtitle there's gotta be a construct for this. `\@!` aka "snail" or something

2017-08-16 18:39 UTC, helgridly approved these changes

2017-08-16 19:02 UTC, merged

2017-08-16 21:30 UTC, rtitle commented on core/src/main/scala/org/broadinstitute/dsde/rawls/expressions/OutputExpression.scala
> +    tryParse(ThisEntityTarget, expr, attribute) recoverWith { case _ => tryParse(WorkspaceTarget, expr, attribute) }
I, uh.... *hides*

2017-08-16 21:40 UTC, helgridly commented on core/src/main/scala/org/broadinstitute/dsde/rawls/expressions/OutputExpression.scala
> +    tryParse(ThisEntityTarget, expr, attribute) recoverWith { case _ => tryParse(WorkspaceTarget, expr, attribute) }
🐌