add canCompute permission
broadinstitute/rawls pull request #787
Opened 2017-09-15 13:50 UTC by dvoet

GAWB-2216

Persistence of this new permission mimics the canShare permission. Behavior is slightly different, it defaults to true for writers and cannot be true for readers. I am not concerned with code duplication as this entire implementation is tech debt anyway. Once sam is in use all this code goes away.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check that the **Product Owner** has signed off on any user-facing changes
- [ ] **Submitter**: Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Database checks:
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] Tell your tech lead (TL) that the PR exists if they want to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-09-15 13:51 UTC, dvoet commented on core/src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceServiceSpec.scala
> -  it should "return conflicts during an entity copy" in {
sorry @MatthewBemis

2017-09-15 13:54 UTC, MatthewBemis commented on core/src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceServiceSpec.scala
> -  it should "return conflicts during an entity copy" in {
RIP

2017-09-15 16:20 UTC, UrsaStutsman approved these changes
Just the one question.. Other than that, looks good to me.

2017-09-15 16:20 UTC, UrsaStutsman commented on core/src/test/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiServiceSpec.scala
> +        responseAs[WorkspaceACL].acl should contain (testData.userReader.userEmail.value -> AccessEntry(WorkspaceAccessLevels.Write, false, false, true))
Not sure if this is part of the req's but should we also test to make sure you can't set owner to false? I have it set up in the UI such that you can't change owner's canCompute access.

2017-09-15 17:13 UTC, MatthewBemis requested changes

2017-09-15 17:13 UTC, MatthewBemis commented on core/src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/slick/WorkspaceComponent.scala
> +    def deleteWorkspaceComputePermissions(workspaceId: UUID) = {
this is never actually called by `deleteWorkspace`

2017-09-15 17:13 UTC, MatthewBemis commented on core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
> +        throw new RawlsExceptionWithErrorReport(ErrorReport(StatusCodes.BadRequest, s"You may not alter the compute permissions of users unless you are a workspace owner. Please correct these entries
the list after "Please correct these entries" is the wrong value- should be `membersWithComputePermission`, which i realize is probably a result of copy-pasting the error message above it which is also wrong

2017-09-19 17:16 UTC, MatthewBemis approved these changes

2017-09-19 17:36 UTC, merged